#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        ddl-auto: false
#    database-platform: org.hibernate.dialect.H2Dialect
#    database: H2
#
#
#logging.level:
#  org.hibernate.SQL: debug