spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hscaudy20@gmail.com
    password: ubbjtnwkvzaiavdq
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: dev

logging.level:
  org.hibernate.SQL: debug

app:
  host: http://127.0.0.1:8080